# Generated by Django 5.2.17 on 2026-08-15 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='🌾', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tag', models.CharField(choices=[('SPECIAL', 'Rabbani Special'), ('GLUTEN_FREE', 'Gluten-Free'), ('PREMIUM', 'Premium'), ('POWER_MIX', 'Power Mix'), ('STANDARD', 'Standard')], default='STANDARD', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination_city', models.CharField(choices=[('Hasan Abdal', 'Hasan Abdal'), ('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Multan', 'Multan'), ('Faisalabad', 'Faisalabad')], default='Hasan Abdal', max_length=50)),
                ('delivery_address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('delivery_fare', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MILLING', 'Milling in Progress'), ('PACKED', 'Packed'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mill.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(choices=[('Hasan Abdal', 'Hasan Abdal'), ('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Multan', 'Multan'), ('Faisalabad', 'Faisalabad')], default='Hasan Abdal', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
